package main

import "strings"

// ✅ Full country name as key - accurate matching
var flagMap = map[string]string{
	"afghanistan":              "🇦🇫",
	"albania":                  "🇦🇱",
	"algeria":                  "🇩🇿",
	"andorra":                  "🇦🇩",
	"angola":                   "🇦🇴",
	"antigua and barbuda":      "🇦🇬",
	"argentina":                "🇦🇷",
	"armenia":                  "🇦🇲",
	"australia":                "🇦🇺",
	"austria":                  "🇦🇹",
	"azerbaijan":               "🇦🇿",
	"bahamas":                  "🇧🇸",
	"bahrain":                  "🇧🇭",
	"bangladesh":               "🇧🇩",
	"barbados":                 "🇧🇧",
	"belarus":                  "🇧🇾",
	"belgium":                  "🇧🇪",
	"belize":                   "🇧🇿",
	"benin":                    "🇧🇯",
	"bhutan":                   "🇧🇹",
	"bolivia":                  "🇧🇴",
	"bosnia and herzegovina":   "🇧🇦",
	"botswana":                 "🇧🇼",
	"brazil":                   "🇧🇷",
	"brunei":                   "🇧🇳",
	"bulgaria":                 "🇧🇬",
	"burkina faso":             "🇧🇫",
	"burundi":                  "🇧🇮",
	"cambodia":                 "🇰🇭",
	"cameroon":                 "🇨🇲",
	"canada":                   "🇨🇦",
	"cape verde":               "🇨🇻",
	"central african republic": "🇨🇫",
	"chad":                     "🇹🇩",
	"chile":                    "🇨🇱",
	"china":                    "🇨🇳",
	"colombia":                 "🇨🇴",
	"comoros":                  "🇰🇲",
	"congo":                    "🇨🇬",
	"costa rica":               "🇨🇷",
	"croatia":                  "🇭🇷",
	"cuba":                     "🇨🇺",
	"cyprus":                   "🇨🇾",
	"czech republic":           "🇨🇿",
	"denmark":                  "🇩🇰",
	"djibouti":                 "🇩🇯",
	"dominica":                 "🇩🇲",
	"dominican republic":       "🇩🇴",
	"ecuador":                  "🇪🇨",
	"egypt":                    "🇪🇬",
	"el salvador":              "🇸🇻",
	"equatorial guinea":        "🇬🇶",
	"eritrea":                  "🇪🇷",
	"estonia":                  "🇪🇪",
	"eswatini":                 "🇸🇿",
	"ethiopia":                 "🇪🇹",
	"finland":                  "🇫🇮",
	"france":                   "🇫🇷",
	"gabon":                    "🇬🇦",
	"gambia":                   "🇬🇲",
	"georgia":                  "🇬🇪",
	"germany":                  "🇩🇪",
	"ghana":                    "🇬🇭",
	"greece":                   "🇬🇷",
	"grenada":                  "🇬🇩",
	"guatemala":                "🇬🇹",
	"guinea":                   "🇬🇳",
	"guinea-bissau":            "🇬🇼",
	"guyana":                   "🇬🇾",
	"haiti":                    "🇭🇹",
	"honduras":                 "🇭🇳",
	"hungary":                  "🇭🇺",
	"iceland":                  "🇮🇸",
	"india":                    "🇮🇳",
	"indonesia":                "🇮🇩",
	"iran":                     "🇮🇷",
	"iraq":                     "🇮🇶",
	"ireland":                  "🇮🇪",
	"israel":                   "🇮🇱",
	"italy":                    "🇮🇹",
	"ivory coast":              "🇨🇮",
	"ivory":                   "🇨🇮",
	"cote":                    "🇨🇮",
	"jamaica":                  "🇯🇲",
	"japan":                    "🇯🇵",
	"jordan":                   "🇯🇴",
	"kazakhstan":               "🇰🇿",
	"kenya":                    "🇰🇪",
	"kiribati":                 "🇰🇮",
	"kuwait":                   "🇰🇼",
	"kyrgyzstan":               "🇰🇬",
	"kosovo":                   "🇽🇰",
	"laos":                     "🇱🇦",
	"latvia":                   "🇱🇻",
	"lebanon":                  "🇱🇧",
	"lesotho":                  "🇱🇸",
	"liberia":                  "🇱🇷",
	"libya":                    "🇱🇾",
	"liechtenstein":            "🇱🇮",
	"lithuania":                "🇱🇹",
	"luxembourg":               "🇱🇺",
	"madagascar":               "🇲🇬",
	"malawi":                   "🇲🇼",
	"malaysia":                 "🇲🇾",
	"maldives":                 "🇲🇻",
	"mali":                     "🇲🇱",
	"malta":                    "🇲🇹",
	"mexico":                   "🇲🇽",
	"mongolia":                 "🇲🇳",
	"morocco":                  "🇲🇦",
	"mozambique":               "🇲🇿",
	"myanmar":                  "🇲🇲",
	"namibia":                  "🇳🇦",
	"nepal":                    "🇳🇵",
	"netherlands":              "🇳🇱",
	"new zealand":              "🇳🇿",
	"nicaragua":                "🇳🇮",
	"niger":                    "🇳🇪",
	"nigeria":                  "🇳🇬",
	"north korea":              "🇰🇵",
	"norway":                   "🇳🇴",
	"oman":                     "🇴🇲",
	"pakistan":                 "🇵🇰",
	"panama":                   "🇵🇦",
	"papua new guinea":         "🇵🇬",
	"paraguay":                 "🇵🇾",
	"peru":                     "🇵🇪",
	"philippines":              "🇵🇭",
	"poland":                   "🇵🇱",
	"portugal":                 "🇵🇹",
	"palestine":                "🇵🇸",
	"qatar":                    "🇶🇦",
	"romania":                  "🇷🇴",
	"russia":                   "🇷🇺",
	"rwanda":                   "🇷🇼",
	"saudi arabia":             "🇸🇦",
	"senegal":                  "🇸🇳",
	"serbia":                   "🇷🇸",
	"sierra leone":             "🇸🇱",
	"singapore":                "🇸🇬",
	"slovakia":                 "🇸🇰",
	"slovenia":                 "🇸🇮",
	"somalia":                  "🇸🇴",
	"south africa":             "🇿🇦",
	"south korea":              "🇰🇷",
	"spain":                    "🇪🇸",
	"sri lanka":                "🇱🇰",
	"sudan":                    "🇸🇩",
	"sweden":                   "🇸🇪",
	"switzerland":              "🇨🇭",
	"syria":                    "🇸🇾",
	"taiwan":                   "🇹🇼",
	"tajikistan":               "🇹🇯",
	"tanzania":                 "🇹🇿",
	"thailand":                 "🇹🇭",
	"tunisia":                  "🇹🇳",
	"turkey":                   "🇹🇷",
	"turkmenistan":             "🇹🇲",
	"uganda":                   "🇺🇬",
	"ukraine":                  "🇺🇦",
	"united arab emirates":     "🇦🇪",
	"united kingdom":           "🇬🇧",
	"united states":            "🇺🇸",
	"usa":                      "🇺🇸",
	"uk":                       "🇬🇧",
	"uae":                      "🇦🇪",
	"uruguay":                  "🇺🇾",
	"uzbekistan":               "🇺🇿",
	"venezuela":                "🇻🇪",
	"vietnam":                  "🇻🇳",
	"yemen":                    "🇾🇪",
	"zambia":                   "🇿🇲",
	"zimbabwe":                 "🇿🇼",
}

func GetCountryWithFlag(countryName string) (string, string) {
	if countryName == "" {
		return "🌐", "🌐 Unknown"
	}

	clean := strings.ToLower(strings.TrimSpace(countryName))

	// ✅ 1. Full name exact match (most accurate)
	if flag, ok := flagMap[clean]; ok {
		return flag, flag + " " + countryName
	}

	// ✅ 2. Partial match - agar "South Korea" aaye to "south korea" dhundho
	for key, flag := range flagMap {
		if strings.Contains(clean, key) {
			return flag, flag + " " + countryName
		}
	}

	// ✅ 3. First word fallback
	words := strings.Fields(clean)
	if len(words) > 0 {
		if flag, ok := flagMap[words[0]]; ok {
			return flag, flag + " " + countryName
		}
	}

	return "🌐", "🌐 " + countryName
}

// Phone number se country detect karo
var dialCodeMap = []struct {
	code    string
	flag    string
	country string
}{
	// 3 digit pehle (priority)
	{"998", "🇺🇿", "Uzbekistan"},
	{"996", "🇰🇬", "Kyrgyzstan"},
	{"995", "🇬🇪", "Georgia"},
	{"994", "🇦🇿", "Azerbaijan"},
	{"993", "🇹🇲", "Turkmenistan"},
	{"992", "🇹🇯", "Tajikistan"},
	{"977", "🇳🇵", "Nepal"},
	{"976", "🇲🇳", "Mongolia"},
	{"975", "🇧🇹", "Bhutan"},
	{"974", "🇶🇦", "Qatar"},
	{"973", "🇧🇭", "Bahrain"},
	{"972", "🇮🇱", "Israel"},
	{"971", "🇦🇪", "UAE"},
	{"970", "🇵🇸", "Palestine"},
	{"968", "🇴🇲", "Oman"},
	{"967", "🇾🇪", "Yemen"},
	{"966", "🇸🇦", "Saudi Arabia"},
	{"965", "🇰🇼", "Kuwait"},
	{"964", "🇮🇶", "Iraq"},
	{"963", "🇸🇾", "Syria"},
	{"962", "🇯🇴", "Jordan"},
	{"961", "🇱🇧", "Lebanon"},
	{"960", "🇲🇻", "Maldives"},
	{"886", "🇹🇼", "Taiwan"},
	{"880", "🇧🇩", "Bangladesh"},
	{"856", "🇱🇦", "Laos"},
	{"855", "🇰🇭", "Cambodia"},
	{"853", "🇲🇴", "Macau"},
	{"852", "🇭🇰", "Hong Kong"},
	{"850", "🇰🇵", "North Korea"},
	{"599", "🇨🇼", "Curacao"},
	{"598", "🇺🇾", "Uruguay"},
	{"597", "🇸🇷", "Suriname"},
	{"595", "🇵🇾", "Paraguay"},
	{"594", "🇬🇫", "French Guiana"},
	{"593", "🇪🇨", "Ecuador"},
	{"592", "🇬🇾", "Guyana"},
	{"591", "🇧🇴", "Bolivia"},
	{"590", "🇬🇵", "Guadeloupe"},
	{"503", "🇸🇻", "El Salvador"},
	{"502", "🇬🇹", "Guatemala"},
	{"501", "🇧🇿", "Belize"},
	{"500", "🇫🇰", "Falkland Islands"},
	{"380", "🇺🇦", "Ukraine"},
	{"375", "🇧🇾", "Belarus"},
	{"374", "🇦🇲", "Armenia"},
	{"373", "🇲🇩", "Moldova"},
	{"372", "🇪🇪", "Estonia"},
	{"371", "🇱🇻", "Latvia"},
	{"370", "🇱🇹", "Lithuania"},
	{"359", "🇧🇬", "Bulgaria"},
	{"358", "🇫🇮", "Finland"},
	{"357", "🇨🇾", "Cyprus"},
	{"356", "🇲🇹", "Malta"},
	{"355", "🇦🇱", "Albania"},
	{"354", "🇮🇸", "Iceland"},
	{"353", "🇮🇪", "Ireland"},
	{"352", "🇱🇺", "Luxembourg"},
	{"351", "🇵🇹", "Portugal"},
	{"350", "🇬🇮", "Gibraltar"},
	{"299", "🇬🇱", "Greenland"},
	{"298", "🇫🇴", "Faroe Islands"},
	{"297", "🇦🇼", "Aruba"},
	{"290", "🇸🇭", "Saint Helena"},
	{"269", "🇰🇲", "Comoros"},
	{"268", "🇸🇿", "Eswatini"},
	{"267", "🇧🇼", "Botswana"},
	{"266", "🇱🇸", "Lesotho"},
	{"265", "🇲🇼", "Malawi"},
	{"264", "🇳🇦", "Namibia"},
	{"263", "🇿🇼", "Zimbabwe"},
	{"262", "🇷🇪", "Reunion"},
	{"261", "🇲🇬", "Madagascar"},
	{"260", "🇿🇲", "Zambia"},
	{"258", "🇲🇿", "Mozambique"},
	{"257", "🇧🇮", "Burundi"},
	{"256", "🇺🇬", "Uganda"},
	{"255", "🇹🇿", "Tanzania"},
	{"254", "🇰🇪", "Kenya"},
	{"253", "🇩🇯", "Djibouti"},
	{"252", "🇸🇴", "Somalia"},
	{"251", "🇪🇹", "Ethiopia"},
	{"250", "🇷🇼", "Rwanda"},
	{"249", "🇸🇩", "Sudan"},
	{"248", "🇸🇨", "Seychelles"},
	{"246", "🇮🇴", "British Indian Ocean"},
	{"245", "🇬🇼", "Guinea-Bissau"},
	{"244", "🇦🇴", "Angola"},
	{"243", "🇨🇩", "DR Congo"},
	{"242", "🇨🇬", "Congo"},
	{"241", "🇬🇦", "Gabon"},
	{"240", "🇬🇶", "Equatorial Guinea"},
	{"239", "🇸🇹", "Sao Tome"},
	{"238", "🇨🇻", "Cape Verde"},
	{"237", "🇨🇲", "Cameroon"},
	{"236", "🇨🇫", "Central African Republic"},
	{"235", "🇹🇩", "Chad"},
	{"234", "🇳🇬", "Nigeria"},
	{"233", "🇬🇭", "Ghana"},
	{"232", "🇸🇱", "Sierra Leone"},
	{"231", "🇱🇷", "Liberia"},
	{"230", "🇲🇺", "Mauritius"},
	{"229", "🇧🇯", "Benin"},
	{"228", "🇹🇬", "Togo"},
	{"227", "🇳🇪", "Niger"},
	{"226", "🇧🇫", "Burkina Faso"},
	{"225", "🇨🇮", "Ivory Coast"},
	{"224", "🇬🇳", "Guinea"},
	{"223", "🇲🇱", "Mali"},
	{"222", "🇲🇷", "Mauritania"},
	{"221", "🇸🇳", "Senegal"},
	{"220", "🇬🇲", "Gambia"},
	{"218", "🇱🇾", "Libya"},
	{"216", "🇹🇳", "Tunisia"},
	{"213", "🇩🇿", "Algeria"},
	{"212", "🇲🇦", "Morocco"},
	// 2 digit
	{"98", "🇮🇷", "Iran"},
	{"95", "🇲🇲", "Myanmar"},
	{"94", "🇱🇰", "Sri Lanka"},
	{"93", "🇦🇫", "Afghanistan"},
	{"92", "🇵🇰", "Pakistan"},
	{"91", "🇮🇳", "India"},
	{"90", "🇹🇷", "Turkey"},
	{"86", "🇨🇳", "China"},
	{"84", "🇻🇳", "Vietnam"},
	{"82", "🇰🇷", "South Korea"},
	{"81", "🇯🇵", "Japan"},
	{"66", "🇹🇭", "Thailand"},
	{"65", "🇸🇬", "Singapore"},
	{"64", "🇳🇿", "New Zealand"},
	{"63", "🇵🇭", "Philippines"},
	{"62", "🇮🇩", "Indonesia"},
	{"61", "🇦🇺", "Australia"},
	{"60", "🇲🇾", "Malaysia"},
	{"58", "🇻🇪", "Venezuela"},
	{"57", "🇨🇴", "Colombia"},
	{"56", "🇨🇱", "Chile"},
	{"55", "🇧🇷", "Brazil"},
	{"54", "🇦🇷", "Argentina"},
	{"53", "🇨🇺", "Cuba"},
	{"52", "🇲🇽", "Mexico"},
	{"51", "🇵🇪", "Peru"},
	{"49", "🇩🇪", "Germany"},
	{"48", "🇵🇱", "Poland"},
	{"47", "🇳🇴", "Norway"},
	{"46", "🇸🇪", "Sweden"},
	{"45", "🇩🇰", "Denmark"},
	{"44", "🇬🇧", "UK"},
	{"43", "🇦🇹", "Austria"},
	{"41", "🇨🇭", "Switzerland"},
	{"40", "🇷🇴", "Romania"},
	{"39", "🇮🇹", "Italy"},
	{"36", "🇭🇺", "Hungary"},
	{"34", "🇪🇸", "Spain"},
	{"33", "🇫🇷", "France"},
	{"32", "🇧🇪", "Belgium"},
	{"31", "🇳🇱", "Netherlands"},
	{"30", "🇬🇷", "Greece"},
	{"27", "🇿🇦", "South Africa"},
	{"20", "🇪🇬", "Egypt"},
	// 1 digit
	{"7", "🇷🇺", "Russia"},
	{"1", "🇺🇸", "USA"},
}

func GetCountryFromPhone(phone string) (string, string) {
	// Sirf digits rakho
	num := ""
	for _, c := range phone {
		if c >= '0' && c <= '9' {
			num += string(c)
		}
	}
	if len(num) == 0 {
		return "Unknown", "🌐"
	}

	// 3 digit se 1 digit tak match karo
	for _, d := range dialCodeMap {
		if strings.HasPrefix(num, d.code) {
			return d.country, d.flag
		}
	}
	return "Unknown", "🌐"
}
